---
## GLANCE ##

  - name: Installing Glance (Ubuntu)
    apt:
      name:
        - glance
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Editing the glance-api file (Ubuntu)
    copy:
      dest: /etc/glance/glance-api.conf
      content: |
        [database]
        connection = mysql+pymysql://glance:GLANCE_DBPASS@controller/glance

        [keystone_authtoken]
        www_authenticate_uri = http://controller:5000
        auth_url = http://controller:5000
        memcached_servers = controller:11211
        auth_type = password
        project_domain_name = Default
        user_domain_name = Default
        project_name = service
        username = glance
        password = GLANCE_PASS

        [paste_deploy]
        flavor = keystone

        [glance_store]
        stores = file,http
        default_store = file
        filesystem_store_datadir = /var/lib/glance/images/
        mode: 0755
    when: ansible_distribution == "Ubuntu"

  - name: Starting the Image service (Ubuntu)
    systemd:
      name: glance-api
      state: started
    when: ansible_distribution == "Ubuntu"
